const test = require('node:test');
const assert = require('node:assert/strict');
if (!process.env.FIRESTORE_EMULATOR_HOST || !process.env.FIREBASE_AUTH_EMULATOR_HOST) throw new Error('This test requires local Firebase emulators.');
const functions = require('../index');
const { getAuth } = require('firebase-admin/auth');
const { getFirestore } = require('firebase-admin/firestore');
const policy = require('../client-onboarding-policy.cjs');
const auth = getAuth(); const db = getFirestore();
const prefix = `onboarding-${Date.now()}`;
const tenantId = `${prefix}-client`;
const adminUid = `${prefix}-admin`; const clientUid = `${prefix}-customer`;
const call = (uid, data) => ({ auth:{uid,token:{}},data });
test('draft -> projections -> client approval -> gated routing; isolated tenants and stale saves denied', async () => {
  await auth.createUser({uid:adminUid,email:`${prefix}-admin@example.test`});
  await auth.setCustomUserClaims(adminUid,{gmsSuperAdmin:true});
  await auth.createUser({uid:clientUid,email:`${prefix}-customer@example.test`});
  const data = {name:'Emulator client',brandName:'Emulator brand',industry:'services',adminEmail:`${prefix}-customer@example.test`,locationId:`location-${prefix}`,phoneNumber:'+13125551234',telnyxPhoneNumberId:'123456789012345678',campaigns:[]};
  const initial = await functions.saveGmsClient.run(call(adminUid,{clientId:tenantId,create:true,revision:0,data}));
  assert.equal(initial.revision,1); assert.equal(initial.lifecycle,'draft'); assert.equal(initial.readiness.ready,false);
  await assert.rejects(functions.saveGmsClient.run(call(clientUid,{clientId:tenantId,revision:1,data})),{code:'permission-denied'});
  await assert.rejects(functions.saveGmsClient.run(call(adminUid,{clientId:tenantId,revision:0,data})),{code:'aborted'});
  await assert.rejects(functions.getGmsClient.run(call(clientUid,{clientId:'unrelated-client'})),{code:'permission-denied'});
  await assert.rejects(functions.saveGmsClient.run(call(adminUid,{clientId:`${prefix}-other`,create:true,revision:0,data})),{code:'already-exists'});
  await assert.rejects(functions.enableGmsClientRouting.run(call(adminUid,{clientId:tenantId,revision:1})),{code:'failed-precondition'});
  const agentUid = `${prefix}-agent`; await auth.createUser({uid:agentUid,email:`${prefix}-agent@example.test`});
  for (const path of [`agentAssignments/${prefix}-assignment`,`agentUsers/${agentUid}/assignments/${tenantId}`]) await db.doc(path).set({tenantId,agentUid,status:'active',role:'agent'});
  await db.doc(`tenants/${tenantId}/documents/creative-one`).set({tenantId,name:'Emulator creative',status:'active',managedBy:'onboarding'});
  data.campaigns = [{id:'program-one',name:'Program',type:'search',source:'Search',agentUids:[agentUid],script:'Script',qualification:'Question',consent:'Consent',adCopy:'Ad copy',documentIds:['creative-one']}];
  const saved = await functions.saveGmsClient.run(call(adminUid,{clientId:tenantId,revision:1,data}));
  assert.equal((await db.doc(`ingestionRoutes/${tenantId}--program-one`).get()).data().status,'paused');
  assert.equal((await db.doc(`tenants/${tenantId}/scripts/program-one`).get()).data().body,'Script');
  const version = saved.campaignVersions['program-one'];
  await assert.rejects(functions.recordGmsCampaignApproval.run(call(adminUid,{clientId:tenantId,campaignId:'program-one',decision:'approved',version})),{code:'permission-denied'});
  await assert.rejects(functions.recordGmsCampaignApproval.run(call(clientUid,{clientId:tenantId,campaignId:'program-one',decision:'approved',version:'old'})),{code:'aborted'});
  await functions.recordGmsCampaignApproval.run(call(clientUid,{clientId:tenantId,campaignId:'program-one',decision:'approved',version}));
  await db.doc(`tenants/${tenantId}/integrations/readiness`).set({configHash:policy.connectionVersion(saved.data),ghlVerified:true,phoneVerified:true,verifiedAtMs:Date.now()});
  const ready = await functions.enableGmsClientRouting.run(call(adminUid,{clientId:tenantId,revision:2}));
  assert.equal(ready.readiness.percent,100); assert.equal(ready.lifecycle,'routing_enabled');
  data.campaigns[0].adCopy = 'Changed ad';
  const changed = await functions.saveGmsClient.run(call(adminUid,{clientId:tenantId,revision:2,data}));
  assert.equal(changed.readiness.ready,false);
  assert.equal((await db.doc(`ingestionRoutes/${tenantId}--program-one`).get()).data().status,'paused');
  assert.equal((await db.collection(`tenants/${tenantId}/auditLogs`).get()).docs.some(d => d.data().action === 'campaign.client_approval'),true);
});
